firma/config/routes.rb
Rails.application.routes.draw do
  get 'client_panel/index'

  devise_for :clients, controllers: { registrations: "clients/registrations"}
  resources :clients
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users

  get 'packages/index'

  get 'packages/new'

  get 'packages/create'

  get 'packages/edit'

  get 'packages/update'

  get 'packages/show'

  get 'packages/destroy'

  get 'orders/index'

  get 'orders/new'

  get 'orders/create'

  get 'orders/edit'

  get 'orders/update'

  get 'orders/show'

  get 'orders/destroy'

  get 'couriers/index'

  get 'couriers/new'

  get 'couriers/create'

  get 'couriers/edit'

  get 'couriers/update'

  get 'couriers/show'

  get 'couriers/destroy'

  get 'dispathers_office/index'

  get 'dispathers_office/new'

  get 'dispathers_office/create'

  get 'dispathers_office/edit'

  get 'dispathers_office/update'

  get 'dispathers_office/show'

  get 'dispathers_office/destroy'

  get 'warehouses/index'

  get 'warehouses/new'

  get 'warehouses/create'

  get 'warehouses/edit'

  get 'warehouses/update'

  get 'warehouses/show'

  get 'warehouses/destory'

  get 'user/index'

  match ':controller(/:action(/:id))', :via => [:get, :post] 

  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

firma/app/views/layouts/_sidebarAdmin.html.erb
<div class="sidebar-menu">
    <ul>
      <a href="/"><li><i class="fa fa-home" aria-hidden="true"></i>HOME</li></a>
      <a href="/user"><li><i class="fa fa-certificate" aria-hidden="true"></i>Panel Administratora</li></a>
      <a href="/clients"><li><i class="fa fa-briefcase" aria-hidden="true"></i>Klienci</li></a>
      <a href="/users"><li><i class="fa fa-certificate" aria-hidden="true"></i>Pracownicy</li></a>
      <a href="/orders"><li><i class="fa fa-certificate" aria-hidden="true"></i>Zamówienia</li></a>
      <a href="/packages"><li><i class="fa fa-certificate" aria-hidden="true"></i>Paczki</li></a>
      <a href="/warehouses"><li><i class="fa fa-certificate" aria-hidden="true"></i>Magazyny</li></a>
      <a href="/dispatchers_office"><li><i class="fa fa-certificate" aria-hidden="true"></i>Dyspozytornie</li></a>
      <a href="/couriers"><li><i class="fa fa-certificate" aria-hidden="true"></i>Kurierzy</li></a>
      <a href="/users/edit"><li><i class="fa fa-cog" aria-hidden="true"></i>Edytuj Dane</li></a>
      <a href="/users/sign_out"><li><i class="fa fa-certificate" aria-hidden="true"></i>Wyloguj się</li></a>
    </ul>
</div>

firma/app/views/layouts/_sidebarClient.html.erb
<div class="sidebar-menu">
    <ul>
      <a href="/"><li><i class="fa fa-home" aria-hidden="true"></i>HOME</li></a>
      <a href="/client_panel"><li><i class="fa fa-certificate" aria-hidden="true"></i>Panel Klienta</li></a>
      <a href="/orders/new"><li><i class="fa fa-briefcase" aria-hidden="true"></i>Nadaj paczkę</li></a>
      <a href="/clients/edit"><li><i class="fa fa-certificate" aria-hidden="true"></i>Edytuj dane</li></a>
      <a href="/clients/sign_out"><li><i class="fa fa-certificate" aria-hidden="true"></i>Wyloguj się</li></a>
    </ul>
</div>

firma/app/views/layouts/_sidebarCourier.html.erb
<div class="sidebar-menu">
    <ul>
      <a href="/"><li><i class="fa fa-home" aria-hidden="true"></i>HOME</li></a>
      <a href="/user"><li><i class="fa fa-certificate" aria-hidden="true"></i>Panel Kuriera</li></a>
      <a href="/orders"><li><i class="fa fa-certificate" aria-hidden="true"></i>Zamówienia</li></a>
      <a href="/packages"><li><i class="fa fa-certificate" aria-hidden="true"></i>Paczki</li></a>
      <a href="/users/edit"><li><i class="fa fa-cog" aria-hidden="true"></i>Edytuj Dane</li></a>
      <a href="/users/sign_out"><li><i class="fa fa-certificate" aria-hidden="true"></i>Wyloguj się</li></a>
    </ul>
</div>

firma/app/views/layouts/_sidebarDispatcher.html.erb
<div class="sidebar-menu">
    <ul>
      <a href="/"><li><i class="fa fa-home" aria-hidden="true"></i>HOME</li></a>
      <a href="/user"><li><i class="fa fa-certificate" aria-hidden="true"></i>Panel Dyspozytora</li></a>
      <a href="/orders"><li><i class="fa fa-certificate" aria-hidden="true"></i>Wszystkie Zamówienia</li></a>
      <a href="/packages"><li><i class="fa fa-certificate" aria-hidden="true"></i>Paczki</li></a>
      <a href="/couriers"><li><i class="fa fa-certificate" aria-hidden="true"></i>Kurierzy</li></a>
      <a href="/users/edit"><li><i class="fa fa-cog" aria-hidden="true"></i>Edytuj Dane</li></a>
      <a href="/users/sign_out"><li><i class="fa fa-certificate" aria-hidden="true"></i>Wyloguj się</li></a>
    </ul>
</div>

firma/app/views/layouts/_sidebarNotLogged.html.erb
<div class="sidebar-menu">
    <ul>
      <a href="/"><li><i class="fa fa-home" aria-hidden="true"></i>HOME</li></a>
      <a href="/clients/sign_in"><li><i class="fa fa-certificate" aria-hidden="true"></i>Panel Klienta</li></a>
      <a href="/users/sign_in"><li><i class="fa fa-certificate" aria-hidden="true"></i>Panel użytkownika</li></a>
    </ul>
</div>

firma/app/views/layouts/_sidebarWarehouse.html.erb
<div class="sidebar-menu">
    <ul>
      <a href="/"><li><i class="fa fa-home" aria-hidden="true"></i>HOME</li></a>
      <a href="/user"><li><i class="fa fa-certificate" aria-hidden="true"></i>Panel Magazyniera</li></a>
      <a href="/packages"><li><i class="fa fa-certificate" aria-hidden="true"></i>Paczki</li></a>
      <a href="/users/edit"><li><i class="fa fa-cog" aria-hidden="true"></i>Edytuj Dane</li></a>
      <a href="/users/sign_out"><li><i class="fa fa-certificate" aria-hidden="true"></i>Wyloguj się</li></a>
    </ul>
</div>

firma/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html>
	<head>
		<meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Firma Transportowa</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    		<!-- Font awesome -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
        <!-- Google Fonts -->
        <link href='https://fonts.googleapis.com/css?family=Lato:400,700,300|Roboto:400,700,300|Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600' rel='stylesheet' type='text/css'>
        <!-- Own style -->
	</head>
	<body class="<%= controller.controller_name%>">
	
    	<header id="index-header">
            <div class="container-fluid">
                <div class="row">
                    <a href="/"><%= image_tag("logo.png", alt: "Logo Kurier") %></a>
                    <ul class="pull-right">
                                            <% if user_signed_in? %>
                                                <li class="pull-left" ><a style="color: red;">Witaj <%= current_user.name%></a></li>
                          <li class="pull-left"><a href="/user">Panel Administratora</a></li>
                                            <% elsif client_signed_in? %>
                                                <li class="pull-left" ><a style="color: red;">Witaj <%= current_client.name%></a></li>
                                                
                                            <% else %>
                                                <li class="pull-left"></li>
                                            <% end %>
                      <li class="pull-left">
                        <% if client_signed_in? %>
                          <%= link_to "Log Out", destroy_client_session_path, :method => :delete %>
                        <% elsif user_signed_in? %>
                                                    <%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
                                                <% else %>
                          <%= link_to('Log In', new_client_session_path)  %>
                        <% end %>
                      </li>
                      <li class="pull-left"><i id="open-sidebar" class="fa fa-bars" aria-hidden="true"></i></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
            </div>
        </header>

        <div id="background-black" class="background-black-disactive"></div>
        <aside id="sidebar" class="sidebar-close">
            <div class="sidebar-header">
                <h5 class="text-center">MENU</h5>
                <i id="close-sidebar" class="fa fa-times pull-right" aria-hidden="true"></i>
            </div>
            <% if user_signed_in?%>
		    			<% if current_user.is_admin %>
		    				<%= render(:partial => "/layouts/sidebarAdmin")%>
		    			<% elsif current_user.is_dispather %>
		    				<%= render(:partial => "/layouts/sidebarDispatcher")%>
		    			<% elsif current_user.is_courier %>
		    				<%= render(:partial => "/layouts/sidebarCourier")%>
		    			<% elsif current_user.is_warehouse %>
		    				<%= render(:partial => "/layouts/sidebarWarehouse")%>
		    			<% end %>
		    		<% elsif client_signed_in? %>
		    			<%= render(:partial => "/layouts/sidebarClient")%>
		    		<% else %>
							<%= render(:partial => "/layouts/sidebarNotLogged")%>
						<% end %>
        </aside>

		<!-- <p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p> -->
		<%= yield %>
        <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
        <!-- Font awsome -->
        <script src="https://use.fontawesome.com/41b9e4af22.js"></script>
        <!-- Own style -->
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	</body>
</html>